'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';

const containerVariants = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.1 } } };
const itemVariants = { hidden: { opacity: 0, y: 10 }, visible: { opacity: 1, y: 0 } };

interface OrchestrateStageProps {
  headers: string[];
  filename: string;
  onProceed: () => void;
}

export default function OrchestrateStage({ headers, filename, onProceed }: OrchestrateStageProps) {
  const [scheduleType, setScheduleType] = useState('daily');
  const [cronExpression, setCronExpression] = useState('0 0 * * *');
  
  const generateDAG = () => {
    const datasetName = filename.replace(/\.[^/.]+$/, "") || 'dataset';
    let schedule = `'@daily'`;
    if (scheduleType === 'hourly') schedule = `'@hourly'`;
    else if (scheduleType === 'weekly') schedule = `'@weekly'`;
    else if (scheduleType === 'custom') schedule = `'${cronExpression}'`;
    
    return `from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import pandas as pd

default_args = {
    'owner': 'aether',
    'depends_on_past': False,
    'start_date': datetime(2023, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'aether_${datasetName}_pipeline',
    default_args=default_args,
    description='Automated pipeline generated by Aether',
    schedule_interval=${schedule},
    catchup=False,
) as dag:

    def extract_data(**kwargs):
        print("Extracting data...")
        # Add your extraction logic here
        return "${datasetName}_raw.csv"

    def transform_data(**kwargs):
        print("Transforming data...")
        # Simulated transformations from Aether Clean Stage
        df = pd.read_csv("${datasetName}_raw.csv")
        df.dropna(inplace=True) # Basic cleaning
        df.to_csv("${datasetName}_clean.csv", index=False)
        return "${datasetName}_clean.csv"

    def load_data(**kwargs):
        print("Loading data...")
        # Add your load logic here
        pass

    extract_task = PythonOperator(
        task_id='extract',
        python_callable=extract_data,
    )

    transform_task = PythonOperator(
        task_id='transform',
        python_callable=transform_data,
    )

    load_task = PythonOperator(
        task_id='load',
        python_callable=load_data,
    )

    extract_task >> transform_task >> load_task
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateDAG());
  };

  const downloadDAG = () => {
    const blob = new Blob([generateDAG()], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const datasetName = filename.replace(/\.[^/.]+$/, "") || 'dataset';
    a.download = `${datasetName}_dag.py`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible" className="stage-content">
      <motion.div variants={itemVariants} className="stage-header flex-between" style={{ marginBottom: '32px' }}>
        <div>
          <h1 className="stage-title" style={{ fontSize: '36px', fontWeight: 800, margin: '0 0 8px 0', letterSpacing: '-0.02em' }}>
            <span style={{ marginRight: '12px' }}>⏱️</span> Pipeline Orchestration
          </h1>
          <p className="stage-sub" style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '16px' }}>Schedule your workflow and generate Apache Airflow DAGs.</p>
        </div>
        <button className="btn btn-primary" onClick={onProceed} style={{ background: 'linear-gradient(135deg, var(--emerald), var(--cyan))', border: 'none', fontWeight: 'bold' }}>
          Monitor Freshness →
        </button>
      </motion.div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }}>
        <motion.div variants={itemVariants} className="card" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div>
            <h3 style={{ margin: '0 0 16px 0', fontSize: '18px' }}>Schedule Configuration</h3>
            <label style={{ display: 'block', fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '8px' }}>Run Frequency</label>
            <select 
              className="search-input" 
              value={scheduleType} 
              onChange={e => setScheduleType(e.target.value)} 
              style={{ width: '100%', padding: '12px', fontSize: '14px', marginBottom: '16px' }}
            >
              <option value="hourly">Hourly (@hourly)</option>
              <option value="daily">Daily (@daily)</option>
              <option value="weekly">Weekly (@weekly)</option>
              <option value="custom">Custom Cron Expression</option>
            </select>

            {scheduleType === 'custom' && (
              <div>
                <label style={{ display: 'block', fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '8px' }}>Cron Expression</label>
                <input 
                  type="text" 
                  className="search-input" 
                  value={cronExpression} 
                  onChange={e => setCronExpression(e.target.value)} 
                  style={{ width: '100%', padding: '12px', fontSize: '14px', fontFamily: 'monospace' }}
                  placeholder="0 0 * * *"
                />
              </div>
            )}
          </div>

          <div style={{ marginTop: 'auto', display: 'flex', gap: '12px' }}>
            <button className="btn btn-secondary" onClick={handleCopy} style={{ flex: 1 }}>Copy DAG</button>
            <button className="btn btn-secondary" onClick={downloadDAG} style={{ flex: 1, borderColor: 'var(--accent)', color: 'var(--accent)' }}>⬇️ Download .py</button>
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="card">
          <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ color: 'var(--cyan)' }}>Apache Airflow</span> DAG Preview
          </h3>
          <pre style={{ background: '#0d1117', padding: '16px', borderRadius: '8px', color: '#c9d1d9', fontSize: '12px', overflowX: 'auto', margin: 0, height: '400px', overflowY: 'auto' }}>
            <code>{generateDAG()}</code>
          </pre>
        </motion.div>
      </div>
    </motion.div>
  );
}
